name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11, 17, 18, 19, 20]
        distribution: ['zulu']
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set JDK from jdk.java.net
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
        if: ${{ matrix.java != '8' && matrix.java != '11' && matrix.java != '17' }}
      - name: Set up older JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
        if: ${{ matrix.java == '8' || matrix.java == '11' || matrix.java == '17' }}
      - name: Print JDK Version
        run: java -version
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
